### ISSUE TITLE
ReferenceError: sodium is not defined

### ISSUE THREAD

**Issue by bennyn** [wireapp/proteus.js#5]
**Code**

```js
var Proteus = require('wireapp-proteus');

ikp = Proteus.keys.IdentityKeyPair.new();
ikp_bytes = ikp.serialise();

console.log('Identity Key Pair', ikp_bytes);
```

**Error**

> ReferenceError: sodium is not defined
    at Function.module.exports.KeyPair.new (D:\dev\projects\wireapp\proteus.js\build\proteus\keys\KeyPair.js:29:26)
    at Function.module.exports.IdentityKeyPair.new (D:\dev\projects\wireapp\proteus.js\build\proteus\keys\IdentityKeyPair.js:26:32)'

**Steps To Reproduce**

- Run `npm install wireapp-proteus@2.0.1`
- Run the code shown above

**Comment by bennyn** [comment]
Interesting is that `KeyPair.coffee` uses `sodium` but it doesn't import it. So there is nothing like:
```coffeescript
sodium = require 'libsodium-wrappers'
```
